### ISSUE TITLE
USER STORY: Submit a poll response

### ISSUE THREAD

**Issue by volausson** [volausson/My-First-Agile-Project#3]
In order to **receive benefit** as a **role**, I can **goal / desire**
## Acceptance Criteria
* Acceptance Criteria 1: The option should be provided as a checkbox
* Acceptance Criteria 2: The checkbox should be “checked” by default
* Acceptance Criteria 3: The option should appear next to the submit button

## Tasks:
- [ ] Update the wiew: the poll design (HTML and CSS) to include the checkbox and to show name of submitter
- [ ] Create new field in model to track username
- [ ] Update controller functions
- [ ] Update unit test scripts
- [ ] Test functionality
