### ISSUE TITLE
USER STORY: Create a poll

### ISSUE THREAD

**Issue by volausson** [volausson/My-First-Agile-Project#4]
In order to **receive benefit** as a **role**, I can **goal / desire**
## Acceptance Criteria
* Acceptance Criteria 1: The poll should disappear at 11:59 PM on the target date
* Acceptance Criteria 2: The real estate of the 'Poll' should be reserved on the home page with a message informing 'Stay tuned, new poll coming soon' 
* Acceptance Criteria 3: The administrator expiry date should be at least 3 days after the current date.

## Tasks:
- [ ] Update admin module view:  poll design (HTML and CSS) to include date picker
- [ ] Update website view: show 'Stay tuned, new poll coming soon'
- [ ] Create JavaScript function to validate the expiry date is at least after 3 days
- [ ] Update controller function
- [ ] Update unit test scripts
- [ ] Test functionality
